apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm/manifest
    repoURL: https://github.com/aburumman/tech_trends 
    targetRevision: HEAD  